apps/hello/app.lisp

I’ve edited the comments to fit with the rest of the app, I would like to know how to bind a click event to the button so it changes the button background to red when I press it.
Cheers :)

Added a button to example

---

README.md

Inspired by https://news.ycombinator.com/item?id=18903375

Updated README.md as per hacker news comment

---

apps/images/app.lisp
apps/terminal/app.lisp

Just learning Lisp and this is my first push request, so pardon if I make a mistake. 
Window for images was too small—maybe only on my screen? Also, bug fix in terminal window where backspace deletes prompt. The left and right arrows on my keyboard output P and O, but I'll save that for next time.

Small bugs

---

apps/edit/app.lisp
apps/edit/input.inc

So far I've just fixed the scrollbar and added a vdu component-get-id so that it doesn't steal focus.
I want to continue making small improvements. I need to plan a few things out before I go too far with the interface. I've got some more buffer functions that I've been working on, and I'll want to fix the structure to use bytes for offset.
A step forward.

Scrollbar fixes and improvements for edit.

---

apps/edit/app.lisp
apps/edit/input.inc
apps/edit/message

Things done:
- Basic new, open, and save functionality. 
- Reasonable cursor implementation
- Proper scrollbar updates 
- A small msg file as a start file. While not necessary, it seems a good way to start for now.
Things I need to do:
- Buffer store operations aren't quite ready. I have code for switching buffers, but I've chosen not to include it yet as I haven't made a way to interface with them yet.
- Add some name filtering to prevent host file system silliness and non-printable ascii codes.
- Add handling of files that don't exist.
- Add a horizontal or vertical listing of open buffers to select.
- I have some clean up to tend to.
- Look at terminal input code and see how input is handled there.
Positive side effects:
- scroll bar and cursor behavior is implemented to update for …

Basic editor functionality

---

apps/edit/app.lisp
apps/edit/input.inc

Apologies for the long response time, and not testing the pull request. This has been tested and works as expected.
I found a mouse cursor bug and fixed it as well.

fixed breakage

---

apps/edit/app.lisp

The file title now appears in the titlebar. Users can scroll through the buffers and close buffers now. Everything seems to be working as expected.
I think next, I would like to add a record list on the side (sort of the like help app) to allow selection of any open buffer.

Updates for edit

---

cmd/argparse.inc
docs/TERMINAL.md

Includes conversion of DSL terms (e.g. clz_command to :clz_command)

Argparse 0.2

---

cmd/argparse.inc
docs/TERMINAL.md

Updated argparse to use keywords
Updated docs for TERMINAL

keywords and docs

---

cmd/argparse.inc
cmd/wc.lisp

Added 'wc' command (word count, line count, character count)
Also fixed argparse defects

New commands

---

cmd/argparse.inc
cmd/head.lisp
cmd/wc.lisp

Tweaked argparse and added 'head' command

More commands

---

cmd/argparse.inc
cmd/head.lisp
cmd/tail.lisp
docs/TERMINAL.md

Added better integer validation (pos only or any)

Updates to argparse and docs

---

lib/argparse/argparse.inc
lib/csv-data/csv-data.inc
lib/xtras/xtras.inc

Leverage the `dictionary` from `xtras.inc`

Argparse rev

---

lib/xtras/xtras.inc

More predicates, utility, dictionary and 'private' functions imbued to environments

More xtras

---

lib/argparse/argparse.inc
lib/xtras/xtras.inc

Simplifications and fixes

---

STATUS.md

Included YAML library information

Updates to STATUS.MD

---

STATUS.md
lib/yaml-data/yaml-data.lisp

Helps when you can save data to a file!

Added write to file for yaml-data

---

class/lisp/boot.inc
lib/xtras/xtras.inc

first, second, last
Added seq? empty? and nempty? predicates to boot.inc
Closes #137

Fix sequence macros

---

lib/argparse/argparse.inc
lib/xtras/xtras.inc

Closes #129
Using properties instead as it is lite-weight and just as flexible if not more so

Removing 'dict' functions

---

lib/yaml-data/emiter.lisp
lib/yaml-data/scanner.lisp

Removed 'prop-entries' in favor of 'entries'

Residual properties update needed

---

lib/yaml-data/scanner.lisp
lib/yaml-data/yaml-data.lisp

Yaml changes

---

lib/yaml-data/commons.lisp
lib/yaml-data/deserialize.lisp
lib/yaml-data/emiter.lisp
lib/yaml-data/serialize.lisp
lib/yaml-data/yaml-data.lisp
lib/yaml-data/yaml-xchange.lisp

Potential to use in mail exchange

Xchange - A lite weight obj->stream->obj conversion

---

lib/xtras/xtras.inc
lib/yaml-data/commons.lisp
lib/yaml-data/deserialize.lisp
lib/yaml-data/emiter.lisp
lib/yaml-data/parser.lisp
lib/yaml-data/serialize.lisp

Fixed YAML output keywriter
Closes #154

Boolean conversions

---

apps/clock/child.lisp
lib/date/date.inc

The date lib does need work. This fixes current issues, but date lib still has many issues to work on. Might want a project page for it. Dealing with time before the epoch, daylight savings,

Added float time for analog clock and fixed dotw.

---

class/lisp/boot.inc

Fixes empty? nempty? for arrays

---

class/lisp/boot.inc
lib/ast/ast.inc
lib/ast/data_ast.inc
lib/class/reflect.inc

Now includes module identifying the source of the class declaration

Update defclass and reflection

---

class/lisp/boot.inc
lib/class/reflect.inc

Had positioned the predicate for the class as the last thing emitting from the macro

Fixed defclass

---

apps/terminal/tui2.lisp
funcs.sh
lib/ipc/ipc_defs.inc

Adds delay/retry to initial establishment of mail-nodes for Logging

Node timeout

---

Makefile
stop.sh

Now it can build from fresh source

Fix Makefile

---

docs/FRAMEBUFFER.md

First pass at explaining exactly how to get CL up and running on ARM PI machines.
Hopefully this can be used and or updated for other systems, like RiscV.
I haven't been able to actually see the FRAMEBUFFER.md file displayed, will fix any errors after commit.

Write Raspberry PI Framebuffer setup documentation
